### ISSUE TITLE
Logging uses interfaces instead of structs

### ISSUE THREAD

**Issue by chinazj** [florianl/go-nflog#21]
Logger and caller's logger cannot be used together.

```
type Logger interface {
        Prinft(args ...string)
}

type Config struct {
         ...
	// Interface to log internals.
	Logger Logger
}
```

**Comment by chinazj** [comment]
This is not a fatal error.But when we use this library as SDK, the application's logger and the nflog's logger are not consistent. It will cause that we get error logs from two files.


```
func main() {
    // application's logger does not use log package.
   f,err := os.OpenFile(...)
   logrus.SetOutput(f)
   logrus.Info("*****")
   // Two loggers writing to one file can cause unexpected errors
   nf, err := nflog.Open(&config{Logger:log.New(f, "", 0)})
}
```

sorry, I don't good at Englinsh.

**Comment by chinazj** [comment]
This is not a fatal error.But when we use this library as SDK, the application's logger and the nflog's logger are not consistent. It will cause that we get error logs from two files.


```
func main() {
    // application's logger does not use log package.
   f,err := os.OpenFile(...)
   logrus.SetOutput(f)
   logrus.Info("*****")
   // Two loggers writing to one file can cause unexpected errors
   nf, err := nflog.Open(&config{Logger:log.New(f, "", 0)})
}
```

sorry, I don't good at Englinsh.

**Comment by florianl** [comment]
Thanks for the reply.
Just because your application logger doesn't satisfy [*log.Logger](https://pkg.go.dev/log#Logger) isn't a strong argument to introduce a breaking change.

As show cased in section [Logger as an io.Writer](https://pkg.go.dev/github.com/Sirupsen/logrus#section-readme) on the [sirupsen/logrus](https://pkg.go.dev/github.com/Sirupsen/logrus) readme you can use `log.SetOutput()` with a [sirupsen/logrus](https://pkg.go.dev/github.com/Sirupsen/logrus) based [io.Writer](https://pkg.go.dev/io#Writer).
